### ISSUE TITLE
Automatic re-connection to Zeppelin server

### ISSUE THREAD

**Issue by yalishevant** [nashikhmin/Zeppelin-Remote-Run#2]
In case or exception (when user does nothing for a long time)
`RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]`
`org.eclipse.jetty.websocket.api.WebSocketException: RemoteEndpoint unavailable, current state [CLOSED], expecting [OPEN or CONNECTED]`

try to reconnect to the server rather than throw Exception in IDE.

**Comment by nashikhmin** [comment]
It was solved in https://github.com/nashikhmin/Zeppelin-Remote-Run/commit/a5da6f8a8a0f7bde4d53763018d3fe511b37768a
